default:
  pre: "{{docker_service}}"

  vars:
    name_prefix: "{{project_name}}"
    watchdog:
      all: yes
  configs:
    server:
      env:
        FLASK_APP: "app/new.py"
        FLASK_RUN_PORT: "5000"
      command: "flask run --host=0.0.0.0 --port=5000"


production:
  configs:
    server:
      networks:
        - name: 'imagiflow_network'
        - name: '{{project_name}}_network'

