docker run  \
	--env-file .env  \
	--shm-size="8g"  \
	--volume "/etc/group:/etc/group:ro"  \
	--volume "/etc/passwd:/etc/passwd:ro"  \
	--volume "/etc/shadow:/etc/shadow:ro"  \
	--volume "/etc/sudoers.d:/etc/sudoers.d:ro"  \
	--env ENV_FOR_DYNACONF=production  \
	--env C_FORCE_ROOT=1  \
	--env MPLCONFIGDIR=/mnt/efs/fs1/caches  \
	--env GDAL_CACHEMAX=256  \
	--env NUMEXPR_MAX_THREADS=8  \
	--network s1_to_ndvi_network  \
	--volume /mnt/efs/fs1/caches:/mnt/efs/fs1/caches  \
	--volume /nfs/storage/data:/nfs/storage/data  \
	--volume /home/ubuntu/egistic/s1_to_ndvi:/home/ubuntu/egistic/s1_to_ndvi  \
	--workdir /home/ubuntu/egistic/s1_to_ndvi "$@"